buildTests:
   stage: build
   script:
      - make tests
   artifacts:
      paths:
         - testAdventure

test:
   stage: test
   script:
      - testAdventure
      - make coverage
      - make memcheck
      - make static
      - make style
   artifacts:
      paths:
         - coverage
      expire_in: 14 days

docs:
   stage: deploy
   script:
      - make docs
   artifacts:
      paths:
         - docs/code
      expire_in: 14 days

